# Generated by Django 4.2.2 on 2025-02-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0002_letter_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["email"],
                "permissions": [("can_view_list_recipients", "Can view list recipients")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]