# Generated by Django 5.1.5 on 2025-02-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_sent", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время первой отправки")),
                ("end_sent", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время окончания отправки")),
                ("status", models.CharField(max_length=20, verbose_name="Статус отправки")),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipients.letter",
                        verbose_name="Сообщение",
                    ),
                ),
                ("recipients", models.ManyToManyField(to="recipients.recipient", verbose_name="Получатели")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["status"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_mailing", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                ("status", models.BooleanField(verbose_name="Статус")),
                ("response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "mailing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mailings.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
                "ordering": ["status"],
            },
        ),
    ]