# Generated by Django 5.1.5 on 2025-02-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("status_ok", "Успешно"), ("status_nok", "Не успешно")], max_length=20, verbose_name="Статус"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("created", "Создана"), ("started", "Запущена"), ("completed", "Завершена")],
                default="created",
                max_length=20,
                verbose_name="Статус отправки",
            ),
        ),
    ]