# Generated by Django 5.1.5 on 2025-02-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_alter_attempt_status_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("status_ok", "Успешно"), ("status_not", "Не успешно")], max_length=20, verbose_name="Статус"
            ),
        ),
    ]