# Generated by Django 4.2.2 on 2025-02-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_attempt_owner_mailing_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [("can_view_list_mailings", "Can view list mailings")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]