# Generated by Django 4.2.2 on 2025-03-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_view_list_mailings", "Can view list mailings"),
                    ("can_stop_mailings", "Can stop mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]