# Generated by Django 4.2.2 on 2025-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активна"),
        ),
    ]